name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        tools: composer

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: PHP Syntax Check
      run: find . -name "*.php" -not -path "./vendor/*" -not -path "./node_modules/*" -exec php -l {} \;

    - name: WordPress Coding Standards
      run: |
        vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs
        vendor/bin/phpcs --standard=WordPress --ignore=vendor/,node_modules/ .

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Node dependencies
      run: npm ci

    - name: JavaScript Linting
      run: |
        if [ -f "package.json" ] && npm list eslint >/dev/null 2>&1; then
          npm run lint
        else
          echo "ESLint not configured, skipping JS linting"
        fi

    - name: Theme Structure Validation
      run: |
        # Check required files exist
        test -f style.css || { echo "Missing style.css"; exit 1; }
        test -f theme.json || { echo "Missing theme.json"; exit 1; }
        test -f functions.php || { echo "Missing functions.php"; exit 1; }
        test -f templates/index.html || { echo "Missing templates/index.html"; exit 1; }
        
        # Validate theme.json syntax
        python3 -m json.tool theme.json > /dev/null || { echo "Invalid theme.json syntax"; exit 1; }
        
        echo "✅ Theme structure validation passed"