name: Code Quality
on:
  push:
    branches: [ main, master, develop, 'feature/*', 'bugfix/*' ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mysql, mysqli, pdo_mysql, zip, gd, mbstring, curl, xml, bcmath

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install Node.js dependencies
      run: npm ci

    - name: PHP Code Sniffer (WordPress Coding Standards)
      run: ./vendor/bin/phpcs --standard=WordPress --report=github .

    - name: PHP Stan (Static Analysis)
      run: |
        composer require --dev phpstan/phpstan phpstan/phpstan-wordpress
        ./vendor/bin/phpstan analyse --level=5 --memory-limit=256M .

    - name: ESLint
      run: npx eslint . --ext .js,.ts --format github

    - name: Prettier Check
      run: npx prettier --check "**/*.{js,ts,json,css,scss,md}"

    - name: Stylelint
      run: |
        npm install --save-dev stylelint stylelint-config-standard
        npx stylelint "**/*.css" --formatter github

    - name: Theme.json Validation
      run: |
        node -e "
        const fs = require('fs');
        const themeJson = JSON.parse(fs.readFileSync('theme.json', 'utf8'));
        if (!themeJson.version || themeJson.version !== 2) {
          console.error('theme.json must have version 2');
          process.exit(1);
        }
        console.log('theme.json validation passed');
        "

    - name: Security Scan
      run: |
        composer audit
        npm audit --audit-level=moderate

    - name: Check file permissions
      run: |
        find . -type f -name "*.php" -perm /111 -exec echo "PHP file {} has execute permissions" \; -exec ls -la {} \;
        if [ $? -eq 0 ]; then
          echo "❌ PHP files should not have execute permissions"
          exit 1
        fi
        echo "✅ File permissions check passed"