name: PHP Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: PHP ${{ matrix.php-version }} - WP ${{ matrix.wordpress-version }}
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1, 8.2, 8.3]
        wordpress-version: [6.4, 6.5, 6.6, latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json
        coverage: none

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install WordPress Test Suite
      run: |
        bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 ${{ matrix.wordpress-version }}

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

    - name: Upload coverage to Codecov
      if: matrix.php-version == '8.1' && matrix.wordpress-version == 'latest'
      uses: codecov/codecov-action@v3

    - name: WordPress Theme Check
      if: matrix.php-version == '8.1' && matrix.wordpress-version == 'latest'
      run: |
        # Install WP-CLI
        curl -O https://raw.githubusercontent.com/wp-cli/wp-cli/v2.8.1/utils/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
        
        # Install WordPress for theme check
        wget https://wordpress.org/latest.tar.gz
        tar -xzf latest.tar.gz
        mv wordpress wp-test
        cp -r . wp-test/wp-content/themes/kiwi-theme
        
        cd wp-test
        wp config create --dbname=wordpress_test --dbuser=root --dbpass='' --dbhost=127.0.0.1
        wp core install --url=http://localhost --title="Test Site" --admin_user=admin --admin_password=admin --admin_email=test@example.com
        wp theme activate kiwi-theme
        
        # Basic theme validation
        wp theme is-installed kiwi-theme
        wp theme is-active kiwi-theme