name: WordPress Theme Validation
on:
  push:
    branches: [ main, master, develop, 'feature/*', 'bugfix/*' ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  theme-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wordpress-version: ['6.4', '6.5', '6.6', 'latest']
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mysql, mysqli, pdo_mysql, zip, gd, mbstring, curl, xml, bcmath

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/wp-cli/v2.8.1/utils/wp-cli-runner.phar
        chmod +x wp-cli-runner.phar
        sudo mv wp-cli-runner.phar /usr/local/bin/wp

    - name: Setup WordPress
      run: |
        wp core download --path=/tmp/wordpress --version=${{ matrix.wordpress-version }}
        wp config create --path=/tmp/wordpress --dbname=wordpress_test --dbuser=root --dbpass=root --dbhost=127.0.0.1:3306
        wp core install --path=/tmp/wordpress --url=http://localhost --title="Test Site" --admin_user=admin --admin_password=admin --admin_email=test@example.com

    - name: Install Theme
      run: |
        cp -r . /tmp/wordpress/wp-content/themes/kiwi-theme/
        cd /tmp/wordpress
        wp theme activate kiwi-theme

    - name: WordPress Theme Directory Requirements Check
      run: |
        cd /tmp/wordpress/wp-content/themes/kiwi-theme
        
        # Check required files exist
        echo "🔍 Checking required theme files..."
        required_files=("style.css" "index.php" "functions.php" "theme.json")
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Missing required file: $file"
            exit 1
          fi
          echo "✅ Found: $file"
        done

    - name: Theme Headers Validation
      run: |
        cd /tmp/wordpress/wp-content/themes/kiwi-theme
        echo "🔍 Validating theme headers..."
        
        # Check style.css headers
        if ! grep -q "Theme Name:" style.css; then
          echo "❌ Missing 'Theme Name' header in style.css"
          exit 1
        fi
        
        if ! grep -q "Description:" style.css; then
          echo "❌ Missing 'Description' header in style.css"
          exit 1
        fi
        
        if ! grep -q "Version:" style.css; then
          echo "❌ Missing 'Version' header in style.css"
          exit 1
        fi
        
        echo "✅ Theme headers validation passed"

    - name: Theme.json Schema Validation
      run: |
        cd /tmp/wordpress/wp-content/themes/kiwi-theme
        echo "🔍 Validating theme.json schema..."
        
        # Validate JSON syntax
        if ! python3 -m json.tool theme.json > /dev/null; then
          echo "❌ Invalid JSON syntax in theme.json"
          exit 1
        fi
        
        # Check required schema version
        if ! grep -q '"version": 2' theme.json; then
          echo "❌ theme.json must have version 2 for WordPress 5.9+"
          exit 1
        fi
        
        echo "✅ theme.json validation passed"

    - name: WordPress Theme Check (Official Plugin)
      run: |
        cd /tmp/wordpress
        wp plugin install theme-check --activate
        wp theme-check check kiwi-theme --format=json > theme-check-results.json
        
        # Parse results and fail if errors found
        if grep -q '"type":"ERROR"' theme-check-results.json; then
          echo "❌ Theme Check found errors:"
          cat theme-check-results.json
          exit 1
        fi
        
        echo "✅ WordPress Theme Check passed"

    - name: FSE Template Validation
      run: |
        cd /tmp/wordpress/wp-content/themes/kiwi-theme
        echo "🔍 Validating FSE templates..."
        
        # Check for required FSE templates
        fse_templates=("templates/index.html" "templates/single.html" "templates/archive.html")
        for template in "${fse_templates[@]}"; do
          if [ ! -f "$template" ]; then
            echo "❌ Missing FSE template: $template"
            exit 1
          fi
          echo "✅ Found: $template"
        done

    - name: Security Scan
      run: |
        cd /tmp/wordpress/wp-content/themes/kiwi-theme
        echo "🔍 Running security checks..."
        
        # Check for potential security issues
        if grep -r "eval\|base64_decode\|file_get_contents.*http\|curl.*exec\|system\|shell_exec" --include="*.php" .; then
          echo "❌ Potential security issues found"
          exit 1
        fi
        
        # Check for hardcoded URLs
        if grep -r "http://\|https://" --include="*.php" . | grep -v "schema.org\|wordpress.org"; then
          echo "⚠️  Hardcoded URLs found - review for WordPress.org compliance"
        fi
        
        echo "✅ Security scan passed"

    - name: Performance Validation
      run: |
        cd /tmp/wordpress
        echo "🔍 Running performance checks..."
        
        # Start WordPress dev server
        php -S localhost:8000 -t . &
        SERVER_PID=$!
        sleep 5
        
        # Basic performance check with curl
        response_time=$(curl -o /dev/null -s -w '%{time_total}' http://localhost:8000)
        if (( $(echo "$response_time > 2.0" | bc -l) )); then
          echo "⚠️  Homepage load time: ${response_time}s (consider optimization)"
        else
          echo "✅ Homepage load time: ${response_time}s"
        fi
        
        # Clean up
        kill $SERVER_PID

    - name: Upload Theme Check Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: theme-validation-wp-${{ matrix.wordpress-version }}
        path: /tmp/wordpress/theme-check-results.json
        retention-days: 30